import {
  IconActivity as Activity,
  IconAlertCircle as AlertCircle,
  IconAlertTriangle as AlertTriangle,
  IconArchive as Archive,
  IconArchiveOff as ArchiveOff,
  IconArrowUp as ArrowUp,
  IconArrowUpRight as ArrowUpRight,
  IconAt as AtSign,
  IconWaveSine as AudioLines,
  IconChartBar as BarChart3,
  IconBell as Bell,
  IconBookmark as Bookmark,
  IconBookmarkFilled as BookmarkFilled,
  IconBrain as Brain,
  IconBug as Bug,
  IconCheck as Check,
  IconCircleCheck as CheckCircle2,
  IconCheck as CheckIcon,
  IconChevronDown as ChevronDown,
  IconChevronDown as ChevronDownIcon,
  IconChevronLeft as ChevronLeft,
  IconChevronLeft as ChevronLeftIcon,
  IconChevronRight as ChevronRight,
  IconChevronRight as ChevronRightIcon,
  IconCircle as CircleIcon,
  IconClipboard as Clipboard,
  IconClock as Clock,
  IconCommand as Command,
  IconCopy as Copy,
  IconCopy as CopyIcon,
  IconCpu as Cpu,
  IconDownload as Download,
  IconEgg as Egg,
  IconExternalLink as ExternalLink,
  IconEye as Eye,
  IconEyeOff as EyeOff,
  IconPhoto as FileImage,
  IconFileText as FileText,
  IconFolderOpen as FolderOpen,
  IconGitBranch as GitBranch,
  IconGitBranch as GitBranchIcon,
  IconGlobe as Globe,
  IconHash as Hash,
  IconHelpCircle as HelpCircle,
  IconPhoto as ImageIcon,
  IconInfoCircle as Info,
  IconKey as KeyRound,
  IconLayersIntersect2 as Layers3,
  IconLayoutDashboard as LayoutDashboard,
  IconLink as Link,
  IconLink as Link2,
  IconLink as LinkIcon,
  IconLoader2 as Loader2,
  IconLoader2 as Loader2Icon,
  IconLock as Lock,
  IconLogin as LogIn,
  IconMail as Mail,
  IconMaximize as Maximize,
  IconMessageCircle as MessageCircle,
  IconMessageQuestion as MessageQuestion,
  IconMessage2 as MessageSquareText,
  IconMicrophone as Mic,
  IconMicrophoneOff as MicOff,
  IconDeviceDesktop as Monitor,
  IconDeviceDesktopAnalytics as MonitorPlay,
  IconMoon as Moon,
  IconDots as MoreHorizontal,
  IconDots as MoreHorizontalIcon,
  IconDotsVertical as MoreVertical,
  IconNotebook as NotebookTabs,
  IconPackage as Package,
  IconPalette as Palette,
  IconLayoutBottombar as PanelBottom,
  IconLayoutSidebar as PanelLeftIcon,
  IconPlayerPause as Pause,
  IconPaw as PawPrint,
  IconPencil as Pencil,
  IconPencil as PencilIcon,
  IconPencil as PencilLine,
  IconPin as Pin,
  IconPlayerPlay as Play,
  IconPlus as Plus,
  IconRefresh as RefreshCw,
  IconRefresh as RefreshCwIcon,
  IconDeviceFloppy as Save,
  IconSearch as Search,
  IconSearch as SearchIcon,
  IconSend as Send,
  IconSettings as Settings,
  IconSettings2 as Settings2,
  IconAdjustmentsHorizontal as SlidersHorizontal,
  IconSquare as Square,
  IconSteeringWheel as SteeringWheel,
  IconPlayerStopFilled as StopFilled,
  IconSun as Sun,
  IconTerminal2 as Terminal,
  IconTrash as Trash2,
  IconUpload as Upload,
  IconUsers as Users,
  IconVolume2 as Volume2,
  IconVolume2 as Volume2Icon,
  IconVolumeOff as VolumeX,
  IconVolumeOff as VolumeXIcon,
  IconTool as Wrench,
  IconX as X,
  IconX as XIcon,
  IconBolt as Zap,
  IconBoltFilled as ZapFilled,
  IconZoomIn as ZoomIn,
  IconZoomOut as ZoomOut
} from '@tabler/icons-react'

export {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArchiveOff,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  AudioLines,
  BarChart3,
  Bell,
  Bookmark,
  BookmarkFilled,
  Brain,
  Bug,
  Check,
  CheckCircle2,
  CheckIcon,
  ChevronDown,
  ChevronDownIcon,
  ChevronLeft,
  ChevronLeftIcon,
  ChevronRight,
  ChevronRightIcon,
  CircleIcon,
  Clipboard,
  Clock,
  Command,
  Copy,
  CopyIcon,
  Cpu,
  Download,
  Egg,
  ExternalLink,
  Eye,
  EyeOff,
  FileImage,
  FileText,
  FolderOpen,
  GitBranch,
  GitBranchIcon,
  Globe,
  Hash,
  HelpCircle,
  ImageIcon,
  Info,
  KeyRound,
  Layers3,
  LayoutDashboard,
  Link,
  Link2,
  LinkIcon,
  Loader2,
  Loader2Icon,
  Lock,
  LogIn,
  Mail,
  Maximize,
  MessageCircle,
  MessageQuestion,
  MessageSquareText,
  Mic,
  MicOff,
  Monitor,
  MonitorPlay,
  Moon,
  MoreHorizontal,
  MoreHorizontalIcon,
  MoreVertical,
  NotebookTabs,
  Package,
  Palette,
  PanelBottom,
  PanelLeftIcon,
  Pause,
  PawPrint,
  Pencil,
  PencilIcon,
  PencilLine,
  Pin,
  Play,
  Plus,
  RefreshCw,
  RefreshCwIcon,
  Save,
  Search,
  SearchIcon,
  Send,
  Settings,
  Settings2,
  SlidersHorizontal,
  Square,
  SteeringWheel,
  StopFilled,
  Sun,
  Terminal,
  Trash2,
  Upload,
  Users,
  Volume2,
  Volume2Icon,
  VolumeX,
  VolumeXIcon,
  Wrench,
  X,
  XIcon,
  Zap,
  ZapFilled,
  ZoomIn,
  ZoomOut
}

export type { Icon as IconComponent } from '@tabler/icons-react'
