import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'user-stories',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [
        'getting-started/quickstart',
        'getting-started/installation',
        'getting-started/platform-support',
        'getting-started/termux',
        'getting-started/nix-setup',
        'getting-started/updating',
        'getting-started/learning-path',
      ],
    },
    {
      type: 'category',
      label: 'Using Hermes',
      collapsed: true,
      items: [
        'user-guide/cli',
        'user-guide/tui',
        'user-guide/desktop',
        'user-guide/windows-native',
        'user-guide/windows-wsl-quickstart',
        'user-guide/configuration',
        'user-guide/managed-scope',
        'user-guide/configuring-models',
        {
          type: 'category',
          label: 'Secrets',
          collapsed: true,
          items: [
            'user-guide/secrets/index',
            'user-guide/secrets/bitwarden',
          ],
        },
        'user-guide/sessions',
        'user-guide/profiles',
        'user-guide/profile-distributions',
        'user-guide/multi-profile-gateways',
        'user-guide/git-worktrees',
        'user-guide/docker',
        'user-guide/security',
        'user-guide/checkpoints-and-rollback',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: true,
      items: [
        'user-guide/features/overview',
        'user-guide/features/tool-gateway',
        {
          type: 'category',
          label: 'Core',
          items: [
            'user-guide/features/tools',
            'user-guide/features/tool-search',
            'user-guide/features/skills',
            'user-guide/features/lsp',
            'user-guide/features/curator',
            'user-guide/features/memory',
            'user-guide/features/memory-providers',
            'user-guide/features/honcho',
            'user-guide/features/context-files',
            'user-guide/features/context-references',
            'user-guide/features/mixture-of-agents',
            'user-guide/features/personality',
            'user-guide/features/skins',
            'user-guide/features/plugins',
            'user-guide/features/built-in-plugins',
          ],
        },
        {
          type: 'category',
          label: 'Automation',
          items: [
            'user-guide/features/cron',
            'reference/automation-blueprints-catalog',
            'user-guide/features/delegation',
            'user-guide/features/kanban',
            'user-guide/features/codex-app-server-runtime',
            'user-guide/features/kanban-tutorial',
            'user-guide/features/kanban-worker-lanes',
            'user-guide/features/goals',
            'user-guide/features/code-execution',
            'user-guide/features/hooks',
            'user-guide/features/batch-processing',
          ],
        },
        {
          type: 'category',
          label: 'Media & Web',
          items: [
            'user-guide/features/voice-mode',
            'user-guide/features/web-search',
            'user-guide/features/x-search',
            'user-guide/features/browser',
            'user-guide/features/computer-use',
            'user-guide/features/vision',
            'user-guide/features/image-generation',
            'user-guide/features/spotify',
            'user-guide/features/pets',
            'user-guide/features/tts',
            'user-guide/features/deliverable-mode',
          ],
        },
        {
          type: 'category',
          label: 'Management',
          items: [
            'user-guide/features/web-dashboard',
            'user-guide/features/extending-the-dashboard',
            'user-guide/features/api-server',
            'user-guide/features/subscription-proxy',
          ],
        },
        {
          type: 'category',
          label: 'Skills',
          collapsed: true,
          items: [
            'reference/skills-catalog',
            'reference/optional-skills-catalog',
            {
              type: 'category',
              label: 'Bundled',
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: 'apple',
                  key: 'skills-bundled-apple',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/apple/apple-apple-notes',
                    'user-guide/skills/bundled/apple/apple-apple-reminders',
                    'user-guide/skills/bundled/apple/apple-findmy',
                    'user-guide/skills/bundled/apple/apple-imessage',
                    'user-guide/skills/bundled/apple/apple-macos-computer-use',
                  ],
                },
                {
                  type: 'category',
                  label: 'autonomous-ai-agents',
                  key: 'skills-bundled-autonomous-ai-agents',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/autonomous-ai-agents/autonomous-ai-agents-claude-code',
                    'user-guide/skills/bundled/autonomous-ai-agents/autonomous-ai-agents-codex',
                    'user-guide/skills/bundled/autonomous-ai-agents/autonomous-ai-agents-hermes-agent',
                    'user-guide/skills/bundled/autonomous-ai-agents/autonomous-ai-agents-opencode',
                  ],
                },
                {
                  type: 'category',
                  label: 'creative',
                  key: 'skills-bundled-creative',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/creative/creative-architecture-diagram',
                    'user-guide/skills/bundled/creative/creative-ascii-art',
                    'user-guide/skills/bundled/creative/creative-ascii-video',
                    'user-guide/skills/bundled/creative/creative-baoyu-infographic',
                    'user-guide/skills/bundled/creative/creative-claude-design',
                    'user-guide/skills/bundled/creative/creative-comfyui',
                    'user-guide/skills/bundled/creative/creative-design-md',
                    'user-guide/skills/bundled/creative/creative-excalidraw',
                    'user-guide/skills/bundled/creative/creative-humanizer',
                    'user-guide/skills/bundled/creative/creative-manim-video',
                    'user-guide/skills/bundled/creative/creative-p5js',
                    'user-guide/skills/bundled/creative/creative-popular-web-designs',
                    'user-guide/skills/bundled/creative/creative-pretext',
                    'user-guide/skills/bundled/creative/creative-sketch',
                    'user-guide/skills/bundled/creative/creative-songwriting-and-ai-music',
                    'user-guide/skills/bundled/creative/creative-touchdesigner-mcp',
                  ],
                },
                {
                  type: 'category',
                  label: 'data-science',
                  key: 'skills-bundled-data-science',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/data-science/data-science-jupyter-live-kernel',
                  ],
                },
                {
                  type: 'category',
                  label: 'dogfood',
                  key: 'skills-bundled-dogfood',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/dogfood/dogfood-dogfood',
                  ],
                },
                {
                  type: 'category',
                  label: 'email',
                  key: 'skills-bundled-email',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/email/email-himalaya',
                  ],
                },
                {
                  type: 'category',
                  label: 'github',
                  key: 'skills-bundled-github',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/github/github-codebase-inspection',
                    'user-guide/skills/bundled/github/github-github-auth',
                    'user-guide/skills/bundled/github/github-github-code-review',
                    'user-guide/skills/bundled/github/github-github-issues',
                    'user-guide/skills/bundled/github/github-github-pr-workflow',
                    'user-guide/skills/bundled/github/github-github-repo-management',
                  ],
                },
                {
                  type: 'category',
                  label: 'media',
                  key: 'skills-bundled-media',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/media/media-gif-search',
                    'user-guide/skills/bundled/media/media-heartmula',
                    'user-guide/skills/bundled/media/media-songsee',
                    'user-guide/skills/bundled/media/media-youtube-content',
                  ],
                },
                {
                  type: 'category',
                  label: 'mlops',
                  key: 'skills-bundled-mlops',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/mlops/mlops-models-audiocraft',
                    'user-guide/skills/bundled/mlops/mlops-huggingface-hub',
                    'user-guide/skills/bundled/mlops/mlops-inference-llama-cpp',
                    'user-guide/skills/bundled/mlops/mlops-evaluation-lm-evaluation-harness',
                    'user-guide/skills/bundled/mlops/mlops-models-segment-anything',
                    'user-guide/skills/bundled/mlops/mlops-inference-vllm',
                    'user-guide/skills/bundled/mlops/mlops-evaluation-weights-and-biases',
                  ],
                },
                {
                  type: 'category',
                  label: 'note-taking',
                  key: 'skills-bundled-note-taking',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/note-taking/note-taking-obsidian',
                  ],
                },
                {
                  type: 'category',
                  label: 'productivity',
                  key: 'skills-bundled-productivity',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/productivity/productivity-airtable',
                    'user-guide/skills/bundled/productivity/productivity-google-workspace',
                    'user-guide/skills/bundled/productivity/productivity-maps',
                    'user-guide/skills/bundled/productivity/productivity-nano-pdf',
                    'user-guide/skills/bundled/productivity/productivity-notion',
                    'user-guide/skills/bundled/productivity/productivity-ocr-and-documents',
                    'user-guide/skills/bundled/productivity/productivity-petdex',
                    'user-guide/skills/bundled/productivity/productivity-powerpoint',
                    'user-guide/skills/bundled/productivity/productivity-teams-meeting-pipeline',
                  ],
                },
                {
                  type: 'category',
                  label: 'research',
                  key: 'skills-bundled-research',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/research/research-arxiv',
                    'user-guide/skills/bundled/research/research-blogwatcher',
                    'user-guide/skills/bundled/research/research-llm-wiki',
                    'user-guide/skills/bundled/research/research-polymarket',
                    'user-guide/skills/bundled/research/research-research-paper-writing',
                  ],
                },
                {
                  type: 'category',
                  label: 'smart-home',
                  key: 'skills-bundled-smart-home',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/smart-home/smart-home-openhue',
                  ],
                },
                {
                  type: 'category',
                  label: 'social-media',
                  key: 'skills-bundled-social-media',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/social-media/social-media-xurl',
                  ],
                },
                {
                  type: 'category',
                  label: 'software-development',
                  key: 'skills-bundled-software-development',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/software-development/software-development-hermes-agent-skill-authoring',
                    'user-guide/skills/bundled/software-development/software-development-node-inspect-debugger',
                    'user-guide/skills/bundled/software-development/software-development-plan',
                    'user-guide/skills/bundled/software-development/software-development-python-debugpy',
                    'user-guide/skills/bundled/software-development/software-development-requesting-code-review',
                    'user-guide/skills/bundled/software-development/software-development-simplify-code',
                    'user-guide/skills/bundled/software-development/software-development-spike',
                    'user-guide/skills/bundled/software-development/software-development-systematic-debugging',
                    'user-guide/skills/bundled/software-development/software-development-test-driven-development',
                  ],
                },
                {
                  type: 'category',
                  label: 'yuanbao',
                  key: 'skills-bundled-yuanbao',
                  collapsed: true,
                  items: [
                    'user-guide/skills/bundled/yuanbao/yuanbao-yuanbao',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Optional',
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: 'autonomous-ai-agents',
                  key: 'skills-optional-autonomous-ai-agents',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/autonomous-ai-agents/autonomous-ai-agents-antigravity-cli',
                    'user-guide/skills/optional/autonomous-ai-agents/autonomous-ai-agents-blackbox',
                    'user-guide/skills/optional/autonomous-ai-agents/autonomous-ai-agents-grok',
                    'user-guide/skills/optional/autonomous-ai-agents/autonomous-ai-agents-honcho',
                    'user-guide/skills/optional/autonomous-ai-agents/autonomous-ai-agents-openhands',
                  ],
                },
                {
                  type: 'category',
                  label: 'blockchain',
                  key: 'skills-optional-blockchain',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/blockchain/blockchain-evm',
                    'user-guide/skills/optional/blockchain/blockchain-hyperliquid',
                    'user-guide/skills/optional/blockchain/blockchain-solana',
                  ],
                },
                {
                  type: 'category',
                  label: 'communication',
                  key: 'skills-optional-communication',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/communication/communication-one-three-one-rule',
                  ],
                },
                {
                  type: 'category',
                  label: 'creative',
                  key: 'skills-optional-creative',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/creative/creative-baoyu-article-illustrator',
                    'user-guide/skills/optional/creative/creative-baoyu-comic',
                    'user-guide/skills/optional/creative/creative-blender-mcp',
                    'user-guide/skills/optional/creative/creative-concept-diagrams',
                    'user-guide/skills/optional/creative/creative-creative-ideation',
                    'user-guide/skills/optional/creative/creative-hyperframes',
                    'user-guide/skills/optional/creative/creative-kanban-video-orchestrator',
                    'user-guide/skills/optional/creative/creative-meme-generation',
                    'user-guide/skills/optional/creative/creative-pixel-art',
                  ],
                },
                {
                  type: 'category',
                  label: 'devops',
                  key: 'skills-optional-devops',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/devops/devops-cli',
                    'user-guide/skills/optional/devops/devops-docker-management',
                    'user-guide/skills/optional/devops/devops-hermes-s6-container-supervision',
                    'user-guide/skills/optional/devops/devops-pinggy-tunnel',
                    'user-guide/skills/optional/devops/devops-watchers',
                  ],
                },
                {
                  type: 'category',
                  label: 'dogfood',
                  key: 'skills-optional-dogfood',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/dogfood/dogfood-adversarial-ux-test',
                  ],
                },
                {
                  type: 'category',
                  label: 'email',
                  key: 'skills-optional-email',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/email/email-agentmail',
                  ],
                },
                {
                  type: 'category',
                  label: 'finance',
                  key: 'skills-optional-finance',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/finance/finance-3-statement-model',
                    'user-guide/skills/optional/finance/finance-comps-analysis',
                    'user-guide/skills/optional/finance/finance-dcf-model',
                    'user-guide/skills/optional/finance/finance-excel-author',
                    'user-guide/skills/optional/finance/finance-lbo-model',
                    'user-guide/skills/optional/finance/finance-merger-model',
                    'user-guide/skills/optional/finance/finance-pptx-author',
                    'user-guide/skills/optional/finance/finance-stocks',
                  ],
                },
                {
                  type: 'category',
                  label: 'gaming',
                  key: 'skills-optional-gaming',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/gaming/gaming-minecraft-modpack-server',
                    'user-guide/skills/optional/gaming/gaming-pokemon-player',
                  ],
                },
                {
                  type: 'category',
                  label: 'health',
                  key: 'skills-optional-health',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/health/health-fitness-nutrition',
                    'user-guide/skills/optional/health/health-neuroskill-bci',
                  ],
                },
                {
                  type: 'category',
                  label: 'mcp',
                  key: 'skills-optional-mcp',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/mcp/mcp-fastmcp',
                    'user-guide/skills/optional/mcp/mcp-mcporter',
                  ],
                },
                {
                  type: 'category',
                  label: 'migration',
                  key: 'skills-optional-migration',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/migration/migration-openclaw-migration',
                  ],
                },
                {
                  type: 'category',
                  label: 'mlops',
                  key: 'skills-optional-mlops',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/mlops/mlops-accelerate',
                    'user-guide/skills/optional/mlops/mlops-training-axolotl',
                    'user-guide/skills/optional/mlops/mlops-chroma',
                    'user-guide/skills/optional/mlops/mlops-clip',
                    'user-guide/skills/optional/mlops/mlops-research-dspy',
                    'user-guide/skills/optional/mlops/mlops-faiss',
                    'user-guide/skills/optional/mlops/mlops-flash-attention',
                    'user-guide/skills/optional/mlops/mlops-guidance',
                    'user-guide/skills/optional/mlops/mlops-huggingface-tokenizers',
                    'user-guide/skills/optional/mlops/mlops-instructor',
                    'user-guide/skills/optional/mlops/mlops-lambda-labs',
                    'user-guide/skills/optional/mlops/mlops-llava',
                    'user-guide/skills/optional/mlops/mlops-modal',
                    'user-guide/skills/optional/mlops/mlops-nemo-curator',
                    'user-guide/skills/optional/mlops/mlops-obliteratus',
                    'user-guide/skills/optional/mlops/mlops-inference-outlines',
                    'user-guide/skills/optional/mlops/mlops-peft',
                    'user-guide/skills/optional/mlops/mlops-pinecone',
                    'user-guide/skills/optional/mlops/mlops-pytorch-fsdp',
                    'user-guide/skills/optional/mlops/mlops-pytorch-lightning',
                    'user-guide/skills/optional/mlops/mlops-qdrant',
                    'user-guide/skills/optional/mlops/mlops-saelens',
                    'user-guide/skills/optional/mlops/mlops-simpo',
                    'user-guide/skills/optional/mlops/mlops-slime',
                    'user-guide/skills/optional/mlops/mlops-stable-diffusion',
                    'user-guide/skills/optional/mlops/mlops-tensorrt-llm',
                    'user-guide/skills/optional/mlops/mlops-torchtitan',
                    'user-guide/skills/optional/mlops/mlops-training-trl-fine-tuning',
                    'user-guide/skills/optional/mlops/mlops-training-unsloth',
                    'user-guide/skills/optional/mlops/mlops-whisper',
                  ],
                },
                {
                  type: 'category',
                  label: 'payments',
                  key: 'skills-optional-payments',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/payments/payments-mpp-agent',
                    'user-guide/skills/optional/payments/payments-stripe-link-cli',
                    'user-guide/skills/optional/payments/payments-stripe-projects',
                  ],
                },
                {
                  type: 'category',
                  label: 'productivity',
                  key: 'skills-optional-productivity',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/productivity/productivity-canvas',
                    'user-guide/skills/optional/productivity/productivity-here-now',
                    'user-guide/skills/optional/productivity/productivity-memento-flashcards',
                    'user-guide/skills/optional/productivity/productivity-shop',
                    'user-guide/skills/optional/productivity/productivity-shopify',
                    'user-guide/skills/optional/productivity/productivity-siyuan',
                    'user-guide/skills/optional/productivity/productivity-telephony',
                  ],
                },
                {
                  type: 'category',
                  label: 'research',
                  key: 'skills-optional-research',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/research/research-bioinformatics',
                    'user-guide/skills/optional/research/research-darwinian-evolver',
                    'user-guide/skills/optional/research/research-domain-intel',
                    'user-guide/skills/optional/research/research-drug-discovery',
                    'user-guide/skills/optional/research/research-duckduckgo-search',
                    'user-guide/skills/optional/research/research-gitnexus-explorer',
                    'user-guide/skills/optional/research/research-osint-investigation',
                    'user-guide/skills/optional/research/research-parallel-cli',
                    'user-guide/skills/optional/research/research-qmd',
                    'user-guide/skills/optional/research/research-scrapling',
                    'user-guide/skills/optional/research/research-searxng-search',
                  ],
                },
                {
                  type: 'category',
                  label: 'security',
                  key: 'skills-optional-security',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/security/security-1password',
                    'user-guide/skills/optional/security/security-godmode',
                    'user-guide/skills/optional/security/security-oss-forensics',
                    'user-guide/skills/optional/security/security-sherlock',
                    'user-guide/skills/optional/security/security-web-pentest',
                  ],
                },
                {
                  type: 'category',
                  label: 'software-development',
                  key: 'skills-optional-software-development',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/software-development/software-development-code-wiki',
                    'user-guide/skills/optional/software-development/software-development-rest-graphql-debug',
                    'user-guide/skills/optional/software-development/software-development-subagent-driven-development',
                  ],
                },
                {
                  type: 'category',
                  label: 'web-development',
                  key: 'skills-optional-web-development',
                  collapsed: true,
                  items: [
                    'user-guide/skills/optional/web-development/web-development-page-agent',
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Messaging Platforms',
      collapsed: true,
      items: [
        'user-guide/messaging/index',
        {
          type: 'category',
          label: 'Popular',
          items: [
            'user-guide/messaging/telegram',
            'user-guide/messaging/discord',
            'user-guide/messaging/slack',
            'user-guide/messaging/whatsapp',
            'user-guide/messaging/whatsapp-cloud',
            'user-guide/messaging/signal',
            'user-guide/messaging/email',
            'user-guide/messaging/sms',
          ],
        },
        {
          type: 'category',
          label: 'Microsoft 365',
          items: [
            'user-guide/messaging/teams',
            'user-guide/messaging/teams-meetings',
            'user-guide/messaging/msgraph-webhook',
          ],
        },
        {
          type: 'category',
          label: 'Chinese platforms',
          items: [
            'user-guide/messaging/dingtalk',
            'user-guide/messaging/feishu',
            'user-guide/messaging/wecom',
            'user-guide/messaging/wecom-callback',
            'user-guide/messaging/weixin',
            'user-guide/messaging/qqbot',
            'user-guide/messaging/yuanbao',
          ],
        },
        {
          type: 'category',
          label: 'Other',
          items: [
            'user-guide/messaging/homeassistant',
            'user-guide/messaging/mattermost',
            'user-guide/messaging/matrix',
            'user-guide/messaging/bluebubbles',
            'user-guide/messaging/photon',
            'user-guide/messaging/google_chat',
            'user-guide/messaging/line',
            'user-guide/messaging/simplex',
            'user-guide/messaging/ntfy',
            'user-guide/messaging/open-webui',
            'user-guide/messaging/webhooks',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [
        'integrations/index',
        'integrations/nous-portal',
        'integrations/providers',
        'user-guide/features/mcp',
        'user-guide/features/acp',
        'user-guide/features/provider-routing',
        'user-guide/features/fallback-providers',
        'user-guide/features/credential-pools',
      ],
    },
    {
      type: 'category',
      label: 'Guides & Tutorials',
      collapsed: true,
      items: [
        'guides/run-nemotron-3-ultra-free',
        'guides/run-hermes-with-nous-portal',
        'guides/tips',
        'guides/local-llm-on-mac',
        'guides/daily-briefing-bot',
        'guides/team-telegram-assistant',
        'guides/python-library',
        'guides/use-mcp-with-hermes',
        'guides/use-soul-with-hermes',
        'guides/use-voice-mode-with-hermes',
        'guides/build-a-hermes-plugin',
        'guides/automate-with-cron',
        'guides/cron-script-only',
        'guides/automation-blueprints',
        'guides/cron-troubleshooting',
        'guides/work-with-skills',
        'guides/delegation-patterns',
        'guides/github-pr-review-agent',
        'guides/webhook-github-pr-review',
        'guides/migrate-from-openclaw',
        'guides/aws-bedrock',
        'guides/azure-foundry',
        'guides/xai-grok-oauth',
        'guides/oauth-over-ssh',
        'guides/microsoft-graph-app-registration',
        'guides/operate-teams-meeting-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      collapsed: true,
      items: [
        'developer-guide/contributing',
        {
          type: 'category',
          label: 'Architecture',
          items: [
            'developer-guide/architecture',
            'developer-guide/agent-loop',
            'developer-guide/prompt-assembly',
            'developer-guide/context-compression-and-caching',
            'developer-guide/gateway-internals',
            'developer-guide/session-storage',
            'developer-guide/provider-runtime',
            'developer-guide/programmatic-integration',
          ],
        },
        {
          type: 'category',
          label: 'Extending',
          items: [
            'developer-guide/adding-tools',
            'developer-guide/adding-providers',
            'developer-guide/adding-platform-adapters',
            'developer-guide/memory-provider-plugin',
            'developer-guide/context-engine-plugin',
            'developer-guide/model-provider-plugin',
            'developer-guide/image-gen-provider-plugin',
            'developer-guide/video-gen-provider-plugin',
            'developer-guide/web-search-provider-plugin',
            'developer-guide/plugin-llm-access',
            'developer-guide/creating-skills',
            'developer-guide/extending-the-cli',
          ],
        },
        {
          type: 'category',
          label: 'Internals',
          items: [
            'developer-guide/tools-runtime',
            'developer-guide/browser-supervisor',
            'developer-guide/acp-internals',
            'developer-guide/cron-internals',
            'developer-guide/trajectory-format',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Command Reference',
          items: [
            'reference/cli-commands',
            'reference/slash-commands',
            'reference/profile-commands',
          ],
        },
        {
          type: 'category',
          label: 'Configuration Reference',
          items: [
            'reference/environment-variables',
            'reference/mcp-config-reference',
            'reference/model-catalog',
          ],
        },
        {
          type: 'category',
          label: 'Tools & Skills Reference',
          items: [
            'reference/tools-reference',
            'reference/toolsets-reference',
            'reference/skills-catalog',
            'reference/optional-skills-catalog',
          ],
        },
        'reference/faq',
      ],
    },
  ],
};

export default sidebars;
